openapi: 3.1.0
info:
  title: Get All Posts API
  description: REST API for retrieving all available posts.
  version: 'v1.0'

servers:
  - url: http://localhost:8080

paths:
  /posts:
    get:
      operationId: get-posts
      description: Retrieve a list of all available posts.
      summary: Get all posts
      parameters:
        - name: location
          in: query
          description: Filter posts by location.
          required: false
          example: boston
          schema:
            type: string
        - name: date
          in: query
          description: Filter posts by date.
          required: false
          example: 01/01/2000
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Posts fetched successfully!
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
              example:
                - postId: "1"
                  userId: "123"
                  image: "pizza.jpg"
                  description: "Pizza and Pasta Available!"
                  location: "Jamaica Plain, USA"
                  dateTime: "2023-01-01T12:00:00Z"
                  availabilityStatus: "Available"
                - postId: "2"
                  userId: "345"
                  image: "spaghetti.jpg"
                  description: "Spaghetti Available!"
                  location: "Roxbury Crossing, USA"
                  dateTime: "2023-01-01T12:00:00Z"
                  availabilityStatus: "Available"
        '404':
          description: Page not found!
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/ErrorResponse"
              example:
                code: "404"
                message: "Page not found!"

components:
  schemas:
    Post:
      type: object
      properties:
        postId:
          type: string
        userId:
          type: string
        image:
          type: string
        description:
          type: string
        location:
          type: string
        dateTime:
          type: string
          format: date-time
        availabilityStatus:
          type: string

    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          description: Error code
          format: int32
        message:
          type: string
          description: Error message
          format: string