openapi: 3.1.0
info:
  title: REST API for PUT COMMENTS
  description: REST API for the Tasty Trails food-sharing application for updating the comments for a post.
  version: 'v1.0'
 
servers:
  - url: http://localhost:8080
 
paths:
  /posts/{postId}/comments:
    put:
      operationId: update-comment
      description: Update a specific comment using its identifier.
      summary: Update a specific comment
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: string
          example: "234"
        - name: commentId
          in: path
          required: true
          schema:
            type: string
          example: "123"
      requestBody:
        required: true
        content:
          application/json:
            schema:
                type: object
                $ref: "#/components/schemas/Comment"
            example:
              userId: "48"
              postId: "234"
              commentId: "123"
              content: "I'll be coming in 5 mins!"
              image: "thumbs-up.jpg"
      responses:
        '200':
          description: Comment updated successfully!
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Comment"
              example:
                userId: "48"
                postId: "456"
                commentId: "123"
                content: "I'll be coming in 5 mins!"
                image: "thumbs-up.jpg"
        '404':
          description: Comment not found!
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/ErrorResponse"
              example:
                code: 404
                message: "Comment not found!"
 
components:
  schemas:
    Comment:
      type: object
      properties:
        userId:
          type: string
        postId:
          type: string
        commentId:
          type: string
        content:
          type: string
        image:
          type: string
 
 
    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          description: Error code
          format: int32
        message:
          type: string
          description: Error message
          format: string